independent_first_frame: false
warp_denoising_step: false
weight_decay: 0.01
same_step_across_blocks: true
last_step_only: false
i2v: false
gc_interval: 50
context_noise: 0
causal: true

prompt_name: MovieGenVideoBench
prompt_path: prompts/MovieGenVideoBench.txt
